export const ERROR_CODES = {
  GENERIC_ERROR: 'ERR_GENERIC',
  UNAUTHORIZED: 'ERR_UNAUTHORIZED',
  INVALID_CREDENTIALS: 'ERR_INVALID_CREDENTIALS',
  INVALID_TOKEN: 'ERR_INVALID_TOKEN',
  TOKEN_EXPIRED: 'ERR_TOKEN_EXPIRED',
  REFRESH_TOKEN_EXPIRED: 'ERR_REFRESH_TOKEN_EXPIRED',
  INTERNAL_SERVER_ERROR: 'ERR_INTERNAL_SERVER_ERROR',
};

export const ERROR_MESSAGES = {
  GENERIC_ERROR: 'An unknown error occurred.',
};
